
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvjqxocrpufhyqkofpcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2anF4b2NycHVmaHlxa29mcGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NjIyNTUsImV4cCI6MjA1NzIzODI1NX0.uCqI4D-oQREov3M-LxyfjTl-BUDOo7GKbtHTbUoWcGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
